### ISSUE TITLE
Crash on Api 9

### ISSUE THREAD

**Issue by vidueirof** [TBaudon/OpenFLMopub#1]
java.lang.NoSuchMethodError: android.view.View.setSystemUiVisibility

at org.haxe.lime.GameActivity.hideSystemUi(GameActivity.java:168)
at org.haxe.lime.GameActivity.onWindowFocusChanged(GameActivity.java:161)

EDIT: Lime problem. Setting the target sdk at 19, in GameActivity Lime tries to show Immersive mode, and crashes in older versions.

**Comment by Tomobodo** [comment]
Hello, thanks for repporting.
I guess I can safely close this as it's finally more related to Lime than the extension ?
